export const ADDCONTACTUS = "ADDCONTACTUS";
export const GETCONTACTUS = "GETCONTACTUS";
export const UPDATECONTACTUS = "UPDATECONTACTUS";
export const DELETECONTACTUS = "DELETECONTACTUS";
export const CONTACT_US_LOADING = "CONTACT_US_LOADING";